### ISSUE TITLE
Can we have a new distribution build with the updateItemAt fix?

### ISSUE THREAD

**Issue by korelogic** [mpociot/TiCollectionView#37]
[UICollectionView cellForRowAtIndexPath:]: unrecognized selector sent to instance 0x7927b800

**Comment by nuno** [comment]
Yeah will nice to download to a new build dist :)

**Comment by skoften** [comment]
same request, because compiling the module manually generates an error after compiling the app:

[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/Trending.build/Debug-iphonesimulator/Trending-universal.build/Objects-normal/i386/Trending normal i386
[ERROR] :  	Ld build/Trending.build/Debug-iphonesimulator/Trending-universal.build/Objects-normal/x86_64/Trending normal x86_64

**Comment by mpociot** [comment]
Version 1.3.1 is now available
